# Generated by Django 5.1.4 on 2025-08-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('cli_direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('cli_telefono', models.CharField(blank=True, max_length=24, null=True)),
                
            ],
            options={
                'db_table': 'CLIENTE',
            },
        ),
    ]
